# Generated by Django 4.1.1 on 2022-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="author", name="id",),
        migrations.RemoveField(model_name="book", name="id",),
        migrations.AddField(
            model_name="author",
            name="idx",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="idx",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
