# Generated by Django 4.1.1 on 2022-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_author_id_remove_book_id_author_idx_book_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="book", name="read_count", field=models.IntegerField(default=0),
        ),
    ]
